// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFvW51yoYRQtlBJ2wK7Il8LMRCxRMYJ5E',
    appId: '1:216289860554:web:e3cdfafc7525cbf260cd33',
    messagingSenderId: '216289860554',
    projectId: 'todo-c39d2',
    authDomain: 'todo-c39d2.firebaseapp.com',
    storageBucket: 'todo-c39d2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQJUMW85_SvhcgVNNaZHZYFRk0Rbc0nhA',
    appId: '1:216289860554:android:cbbb982e43bd695160cd33',
    messagingSenderId: '216289860554',
    projectId: 'todo-c39d2',
    storageBucket: 'todo-c39d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAEhUW9ggiI7Nu-jPOxKQZnahEPzPX4as',
    appId: '1:216289860554:ios:23452ee7ef6ff7bc60cd33',
    messagingSenderId: '216289860554',
    projectId: 'todo-c39d2',
    storageBucket: 'todo-c39d2.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAEhUW9ggiI7Nu-jPOxKQZnahEPzPX4as',
    appId: '1:216289860554:ios:725567b1ac67a8d360cd33',
    messagingSenderId: '216289860554',
    projectId: 'todo-c39d2',
    storageBucket: 'todo-c39d2.appspot.com',
    iosBundleId: 'com.example.todo.RunnerTests',
  );
}
